//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinalResult08030822
    {
        public double ResultID { get; set; }
        public string ChosedAction { get; set; }
        public Nullable<double> Value1 { get; set; }
        public Nullable<double> Value2 { get; set; }
        public string Marker { get; set; }
        public string TimeRecord { get; set; }
        public string LabeledAction { get; set; }
    }
}
