//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paste
    {
        public int Id { get; set; }
        public Nullable<double> light { get; set; }
        public Nullable<double> xAcce { get; set; }
        public Nullable<double> yAcce { get; set; }
        public Nullable<double> zAcce { get; set; }
        public Nullable<double> angle { get; set; }
        public Nullable<double> azimuth { get; set; }
        public Nullable<double> pitch { get; set; }
        public Nullable<double> roll { get; set; }
        public Nullable<double> latitude { get; set; }
        public Nullable<double> longitude { get; set; }
        public Nullable<double> altitude { get; set; }
        public Nullable<double> hour { get; set; }
        public Nullable<double> moving { get; set; }
        public Nullable<double> turning { get; set; }
        public Nullable<double> lightChanging { get; set; }
        public Nullable<double> dark { get; set; }
        public Nullable<double> accel { get; set; }
        public Nullable<double> status { get; set; }
        public Nullable<double> screenOn { get; set; }
        public Nullable<double> earPlug { get; set; }
        public Nullable<double> sound { get; set; }
        public string activity { get; set; }
    }
}
